/** Renders JSON-LD structured data. Server component — no client cost. */
export function JsonLd({ json, id }: { json: string; id?: string }) {
  return (
    <script
      type="application/ld+json"
      id={id}
      // Structured data is generated by lib/seo.ts from typed objects only.
      dangerouslySetInnerHTML={{ __html: json }}
    />
  );
}
