import manifest from "./asset-manifest.json";

/**
 * Asset availability.
 *
 * The manifest is generated by `scripts/sync-assets.mjs`, which runs before
 * `next dev` and `next build` (see package.json). Importing it as a module — rather
 * than probing the filesystem at render time — keeps asset state inside the
 * compiler's dependency graph, so dropping a file into `public/` always
 * invalidates the right cache entries instead of silently reusing a stale render.
 *
 * Nothing here touches `node:fs`, so this module is safe to import from client
 * components as well as server ones.
 */

export type AppScreenKey = "home" | "wallet" | "sub-wallet" | "payout" | "activity";

/** Aspect ratio assumed for a vector lockup whose intrinsic size is unknown. */
const SVG_LOCKUP_ASPECT = 3.2;

type ManifestScreenshotKey = keyof typeof manifest.screenshots;

export type AppAssets = {
  screenshots: Record<AppScreenKey, string | null>;
  /** True when at least one real screenshot is present. */
  hasRealScreenshots: boolean;
  logo: string | null;
  /** Intrinsic aspect (width ÷ height) of the supplied lockup, for correct scaling. */
  logoAspect: number;
  mark: string | null;
  demoVideo: string | null;
  demoVideoPoster: string | null;
};

function toUrl(value: string | null): string | null {
  return value ? `/${value}` : null;
}

export function getAppAssets(): AppAssets {
  const screenshots = Object.fromEntries(
    (Object.keys(manifest.screenshots) as ManifestScreenshotKey[]).map((key) => [
      key,
      toUrl(manifest.screenshots[key]),
    ]),
  ) as Record<AppScreenKey, string | null>;

  return {
    screenshots,
    hasRealScreenshots: Object.values(screenshots).some(Boolean),
    logo: toUrl(manifest.logo),
    logoAspect: manifest.logoAspect ?? SVG_LOCKUP_ASPECT,
    mark: toUrl(manifest.mark),
    demoVideo: toUrl(manifest.demoVideo),
    demoVideoPoster: toUrl(manifest.demoVideoPoster),
  };
}

/** The raw manifest, for scripts and diagnostics that need the file paths. */
export const assetManifest = manifest;
