/**
 * Asset manifest generator.
 *
 * Next's compiler cannot see `fs.existsSync` calls, so a build could be served
 * from cache after an asset was dropped into `public/`. This script probes the
 * public directory and writes `lib/asset-manifest.json`, which the app imports —
 * a real build input, so adding a file always invalidates the right cache
 * entries. It runs automatically before `next dev` and `next build`.
 *
 * Usage: npm run assets:sync   (also runs as predev / prebuild)
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const publicDir = join(root, "public");
const manifestPath = join(root, "lib", "asset-manifest.json");

const PNG_SIGNATURE = "89504e470d0a1a0a";

const has = (relativePath) => existsSync(join(publicDir, relativePath));
const first = (candidates) => candidates.find(has) ?? null;

/** Intrinsic PNG size from the IHDR chunk — no image library required. */
function readPngSize(relativePath) {
  try {
    const header = readFileSync(join(publicDir, relativePath)).subarray(0, 24);
    if (header.length < 24 || header.toString("hex", 0, 8) !== PNG_SIGNATURE) return null;
    return { width: header.readUInt32BE(16), height: header.readUInt32BE(20) };
  } catch {
    return null;
  }
}

const screenshotCandidates = {
  home: ["images/app/home.png", "images/app/home.webp"],
  wallet: ["images/app/wallet.png", "images/app/wallet.webp"],
  "sub-wallet": ["images/app/sub-wallet.png", "images/app/sub-wallet.webp"],
  payout: ["images/app/payout.png", "images/app/payout.webp"],
  activity: ["images/app/activity.png", "images/app/activity.webp"],
};

const logo = first([
  "images/marketing/dispense-logo.svg",
  "images/marketing/dispense-logo.png",
  "dispense-word-logo.png",
]);
const mark = first(["images/marketing/dispense-mark.svg", "images/marketing/dispense-mark.png"]);

const logoSize = logo && logo.endsWith(".png") ? readPngSize(logo) : null;

const manifest = {
  $comment:
    "Generated by scripts/sync-assets.mjs (npm run assets:sync). Do not edit by hand.",
  logo,
  logoAspect: logoSize ? Number((logoSize.width / logoSize.height).toFixed(3)) : null,
  mark,
  screenshots: Object.fromEntries(
    Object.entries(screenshotCandidates).map(([key, candidates]) => [key, first(candidates)]),
  ),
  demoVideo: first(["media/dispense-demo.mp4"]),
  demoVideoPoster: first(["media/dispense-demo-poster.jpg", "media/dispense-demo-poster.png"]),
};

/* Housekeeping: report stray files so the public directory stays intentional. */
const strayInMedia = existsSync(join(publicDir, "media"))
  ? readdirSync(join(publicDir, "media")).filter(
      (file) => !["dispense-demo.mp4", "dispense-demo-poster.jpg", "dispense-demo-poster.png"].includes(file),
    )
  : [];

writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

const present = [
  manifest.logo ? "logo" : null,
  manifest.mark ? "mark" : null,
  Object.values(manifest.screenshots).filter(Boolean).length > 0
    ? `${Object.values(manifest.screenshots).filter(Boolean).length}/5 screenshots`
    : null,
  manifest.demoVideo ? "demo video" : null,
].filter(Boolean);

console.log(
  `assets: ${present.length > 0 ? present.join(", ") : "placeholders only"} → lib/asset-manifest.json`,
);
if (strayInMedia.length > 0) {
  console.log(`assets: note — unlisted files in public/media: ${strayInMedia.join(", ")}`);
}
